### ISSUE TITLE
Empty results

### ISSUE THREAD

**Issue by aojielian** [mjafin/scalpel#1]
I am using Scalpel to call de novo indels recently, but i cannot get the results.
This is my command:
scalpel-discovery --denovo --dad /projects/ps-sebat1/genomicsdataanalysis/autism/wgsandarrays/fullstudy/REACH/lotone/families/F0122/LP6005396-DNA_B05/sequencingdata/bqsr/LP6005396-DNA_B05-sorted-rmdups-realigned-bqsr-NoBIBD.bam --mom /projects/ps-sebat1/genomicsdataanalysis/autism/wgsandarrays/fullstudy/REACH/lotone/families/F0122/LP6005396-DNA_A05/sequencingdata/bqsr/LP6005396-DNA_A05-sorted-rmdups-realigned-bqsr-NoBIBD.bam --aff /projects/ps-sebat1/genomicsdataanalysis/autism/wgsandarrays/fullstudy/REACH/lotone/families/F0122/LP6005396-DNA_H04/sequencingdata/bqsr/LP6005396-DNA_H04-sorted-rmdups-realigned-bqsr-NoBIBD.bam --sib /projects/ps-sebat1/genomicsdataanalysis/autism/wgsandarrays/fullstudy/REACH/lotone/families/F0122/LP6005396-DNA_C05/sequencingdata/bqsr/LP6005396-DNA_C05-sorted-rmdups-realigned-bqsr-NoBIBD.bam  --bed /home/a1lian/human_hg37.bed --ref /oasis/scratch/comet/mgujral/temp_project/broad_bundles/2.8/b37/human_g1k_v37.fasta 

this job has been running for a long time and the result is a directory like outdir/main/mom/
in the mom/ directory. there are some files like :
bamfile.bam  bamfile.bam.bai  header.txt  parameters.txt  readgroups.txt  regions-0-30953341.fa

**Comment by mjafin** [comment]
Hi @aojielian, 
Thanks for highlighting this issue. This repository is a fork of https://sourceforge.net/projects/scalpel/ from around 5 years ago. I haven't kept it up to date with the original Scalpel algorithm at all so I would recommend cloning Scalpel instead and posting any issues to the author (Giuseppe Narzisi)
